---
repos:
  - repo: local
    hooks:
      - id: fish_indent
        name: "fish indent"
        language: system
        entry: fish_indent --write
        types: [fish]
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.0.2
    hooks:
      - id: stylua-github
