[commands.nvim]
type = "archive_binary"
version = "0.11.6"
url = "https://github.com/neovim/neovim/releases/download/v{version}/nvim-linux-{arch}.tar.gz"
file_copies = [
  { source = "nvim-linux-{arch}", destination = ".local", mode = "rsync-tree" },
]

[[commands.nvim.arch]]
arch = "x86_64"
sha256 = "2fc90b962327f73a78afbfb8203fd19db8db9cdf4ee5e2bef84704339add89cc"

[[commands.nvim.arch]]
arch = "arm64"
sha256 = "8ddc0c101846145e830b17bbca50782ca9307eee4fab539d9e2ddaf8793c06f1"

[commands.rg]
type = "archive_binary"
version = "14.1.0"
url = "https://github.com/BurntSushi/ripgrep/releases/download/{version}/ripgrep-{version}-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "ripgrep-{version}-{arch}-{variant}/rg", destination = ".local/bin/rg" },
  { source = "ripgrep-{version}-{arch}-{variant}/complete/rg.fish", destination = ".config/fish/completions/rg.fish" },
]

[[commands.rg.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "f84757b07f425fe5cf11d87df6644691c644a5cd2348a2c670894272999d3ba7"

[[commands.rg.arch]]
arch = "aarch64"
variant = "unknown-linux-gnu"
sha256 = "c8c210b99844fbf16b7a36d1c963e8351bca5ff2dd7c788f5fba4ac18ba8c60d"

[commands.delta]
type = "archive_binary"
version = "0.18.2"
url = "https://github.com/dandavison/delta/releases/download/{version}/delta-{version}-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "delta-{version}-{arch}-{variant}/delta", destination = ".local/bin/delta" },
]

[[commands.delta.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "b7ea845004762358a00ef9127dd9fd723e333c7e4b9cb1da220c3909372310ee"

[[commands.delta.arch]]
arch = "aarch64"
variant = "unknown-linux-gnu"
sha256 = "adf7674086daa4582f598f74ce9caa6b70c1ba8f4a57d2911499b37826b014f9"

[commands.bat]
type = "archive_binary"
version = "0.26.1"
url = "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "bat-v{version}-{arch}-{variant}/bat", destination = ".local/bin/bat" },
  { source = "bat-v{version}-{arch}-{variant}/autocomplete/bat.fish", destination = ".config/fish/completions/bat.fish" },
]

[[commands.bat.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "0dcd8ac79732c0d5b136f11f4ee00e581440e16a44eab5b3105b611bbf2cf191"

[[commands.bat.arch]]
arch = "aarch64"
variant = "unknown-linux-musl"
sha256 = "6369242c584065f195fb20cb36fbd7cb63ae690605bbe89868a7596b596c2c23"

[commands.eza]
type = "archive_binary"
version = "0.23.4"
url = "https://github.com/eza-community/eza/releases/download/v{version}/eza_{arch}-{variant}.tar.gz"
file_copies = [
  { source = "eza", destination = ".local/bin/eza" },
]

[[commands.eza.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "d231bb3ee33b08c76279b5888845dceb7034d055c42bb9be46dbe0dae39394df"

[[commands.eza.arch]]
arch = "aarch64"
variant = "unknown-linux-gnu"
sha256 = "366e8430225f9955c3dc659b452150c169894833ccfef455e01765e265a3edda"

[commands.fd]
type = "archive_binary"
version = "10.3.0"
url = "https://github.com/sharkdp/fd/releases/download/v{version}/fd-v{version}-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "fd-v{version}-{arch}-{variant}/fd", destination = ".local/bin/fd" },
  { source = "fd-v{version}-{arch}-{variant}/autocomplete/fd.fish", destination = ".config/fish/completions/fd.fish" },
]

[[commands.fd.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "2b6bfaae8c48f12050813c2ffe1884c61ea26e750d803df9c9114550a314cd14"

[[commands.fd.arch]]
arch = "aarch64"
variant = "unknown-linux-musl"
sha256 = "996b9b1366433b211cb3bbedba91c9dbce2431842144d925428ead0adf32020b"

[commands.lua_ls]
type = "archive_extract"
version = "3.17.1"
url = "https://github.com/LuaLS/lua-language-server/releases/download/{version}/lua-language-server-{version}-linux-{arch}.tar.gz"
destination = ".local/share/lua_ls"
wrapper_path = ".local/bin/lua-language-server"
wrapper_exec = ".local/share/lua_ls/bin/lua-language-server"

[[commands.lua_ls.arch]]
arch = "x64"
sha256 = "248b0858a0afc8233f2535e89b648398b2202cb96cf51ce187e3263923dd0223"

[[commands.lua_ls.arch]]
arch = "arm64"
sha256 = "680285a36d8cf7b17ca4be7a2f9c93643ebd8daec0b7425a6b7a02d003f3da81"

[commands.rust-analyzer]
type = "rustup_component"
component = "rust-analyzer"

[commands.just]
type = "archive_binary"
version = "1.46.0"
url = "https://github.com/casey/just/releases/download/{version}/just-{version}-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "just", destination = ".local/bin/just" },
  { source = "just.1", destination = ".local/share/man/man1/just.1" },
  { source = "completions/just.fish", destination = ".config/fish/completions/just.fish" },
]

[[commands.just.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "79966e6e353f535ee7d1c6221641bcc8e3381c55b0d0a6dc6e54b34f9db36eaa"

[[commands.just.arch]]
arch = "aarch64"
variant = "unknown-linux-musl"
sha256 = "b81970c8247fa64cfb30d2a3da0e487e4253f9f2d01865ed5e7d53cdc7b02188"

[commands.uv]
type = "archive_binary"
version = "0.10.9"
url = "https://github.com/astral-sh/uv/releases/download/{version}/uv-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "uv-{arch}-{variant}", destination = ".local/bin", mode = "dircopy" },
]

[[commands.uv.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "433e56874739e92c7cfd661ba9e5f287b376ca612c08c8194a41a98a13158aea"

[[commands.uv.arch]]
arch = "aarch64"
variant = "unknown-linux-musl"
sha256 = "05b0d3087e913ebe11756365a90dd47c05d6728752fdbe129ad4c3ccd769826d"

[commands.jj]
type = "archive_binary"
version = "0.39.0"
url = "https://github.com/jj-vcs/jj/releases/download/v{version}/jj-v{version}-{arch}-{variant}.tar.gz"
file_copies = [
  { source = "jj", destination = ".local/bin/jj"},
]

[[commands.jj.arch]]
arch = "x86_64"
variant = "unknown-linux-musl"
sha256 = "8da8d96e9c8696c21ad47847a63d533e249acb0449d9af0f0562b5ea7b024f04"

[[commands.jj.arch]]
arch = "aarch64"
variant = "unknown-linux-musl"
sha256 = "15bbb0199adf57929d1e3cd90ae0b47356858cbe374814769815a1fb87d5ad1d"

[commands.fish]
type = "archive_binary"
version = "4.5.0"
url = "https://github.com/fish-shell/fish-shell/releases/download/{version}/fish-{version}-linux-{arch}.tar.xz"
file_copies = [
  { source = "fish", destination = ".local/bin/fish"},
]

[[commands.fish.arch]]
arch = "x86_64"
sha256 = "a78d17517a6772a616d214a63f163ba8281c70834b71eeae9d1a37267e9e46d3"

[[commands.fish.arch]]
arch = "aarch64"
sha256 = "e99e3dd09ee31f40e3a12ea4410ebaf50006f26277ce5153189648baae5e141d"

[commands.typescript-language-server]
type = "npm_global"
packages = ["typescript", "typescript-language-server"]

[commands.tailwindcss-language-server]
type = "npm_global"
packages = ["@tailwindcss/language-server"]

[commands.css-language-server]
type = "npm_global"
packages = ["vscode-langservers-extracted"]

[commands.html-language-server]
type = "npm_global"
packages = ["vscode-langservers-extracted"]

[commands.opencode]
type = "npm_global"
packages = ["opencode-ai@latest"]

[commands.copilot-language-server]
type = "npm_global"
packages = ["@github/copilot-language-server"]

[commands.gopls]
type = "go_install"
package = "golang.org/x/tools/gopls@latest"

[commands.pre-commit]
type = "uv_tool"
package = "pre-commit"
post_install_pre_commit_hook = true

[commands.ty]
type = "uv_tool"
package = "ty@latest"

[commands.rustfmt]
type = "rustup_component"
component = "rustfmt"
