#!/bin/bash
set -exo pipefail

HERE=$(pwd)

files=("vim" "bashrc")
for file in "${files[@]}"
do
    rm -rf "$HOME/.$file"
    ln -s "$HERE/$file" "$HOME/.$file"
done

mkdir -p $HOME/.config
ls xdg_config | xargs -I+ ln -s "$HERE/xdg_config/+" $HOME/.config/
