steps:
  - label: ":fish: :white_check_mark: Run linters"
    key: "lint"
    command: |
      export PATH="$HOME/.local/bin:$PATH"
      python3 scripts/cmd_install.py uv stylua ty ruff fish just
      ln -s ~/.local/bin/fish ~/.local/bin/fish_indent
      just check
    plugins:
      - docker#v5.13.0:
          image: "python:3.14-trixie"
