---
name: Run linters
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          python scripts/cmd_install.py uv stylua ty ruff fish just
          ln -s ~/.local/bin/fish ~/.local/bin/fish_indent

      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Check code
        run: just check
