---
name: Run linters
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install/setup fish
        run: sudo apt-get install -y fish

      - name: Set up Python for pre-commit
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pre-commit
        run: pip3 install pre-commit

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files --show-diff-on-failure
